project_id = "pnmipcfdjkqhurgzpjam"

[functions.send-message-notification]
verify_jwt = false

[functions.notify-job-posted]
verify_jwt = false

[functions.welcome-new-user]
verify_jwt = false

[functions.notify-proposal-received]
verify_jwt = false
